### PR TITLE
Support display operator metrics

### PR DESCRIPTION
**Pull request by yeya24**
Signed-off-by: yeya24 <yb532204897@gmail.com>

Fixes https://issues.redhat.com/browse/OSD-3954

Usage

```
osd-utils-cli metrics -h
display metrics of aws-account-operator

Options:
      --account-namespace='aws-account-operator': The namespace to keep AWS accounts. The default value is
aws-account-operator.
      --route='aws-account-operator': The route created for aws-account-operator
      --sa='aws-account-operator': The service account name for aws-account-operator

Usage:
  osd-utils-cli metrics [flags] [options]

Use "osd-utils-cli options" for a list of global command-line options (applies to all commands).
```

### CODE REVIEW

**Comment by rogbas** [comment]
@rogbas @clcollins please give it a try in hive-stage and comment

**Comment by yeya24** [comment]
Screenshot from 2020-06-15 14-08-35

Add another flag `-m` to optionally specify the aws-account-operator metrics URL, used in local debug case.

**Comment by yeya24** [comment]
This one is rebased. Please do a test, thank you! @clcollins 

The basic usage is `osd-utils-cli metrics` if you are at openshift environment

**Comment by clcollins** [comment]
/hold

@yeya24 Can you add you v3/v4 fix to this PR and squash, and then we can test and merge it.

**Pull request merged**
