### PR TITLE
Match related objects between AWS account and operator crs

### PR DESCRIPTION
**Pull request by yeya24**
Signed-off-by: yeya24 <yb532204897@gmail.com>

### CODE REVIEW

**Comment by clcollins** [comment]
@yeya24 This is looking really good.  I love they way this works, and it'll save a lot of time for us!  The JSON and YAML output of the full object is fantastic, too.

Regarding:

```
osd-utils-cli get account -i <Account ID>
osd-utils-cli get account-claim <Account ID>
osd-utils-cli get aws-account -a <Account CR Name>
```

Can you be more consistent about where flags and positional arguments are used?  Pick one and do it that way, just for easy of use for the rest of the team.

I'm excited for this feature! We do this kind of stuff ALL THE TIME, so it will be a huge timesaver!

**Comment by yeya24** [comment]
> @yeya24 This is looking really good. I love they way this works, and it'll save a lot of time for us! The JSON and YAML output of the full object is fantastic, too.
> 
> Regarding:
> 
> ```
> osd-utils-cli get account -i <Account ID>
> osd-utils-cli get account-claim <Account ID>
> osd-utils-cli get aws-account -a <Account CR Name>
> ```
> 
> Can you be more consistent about where flags and positional arguments are used? Pick one and do it that way, just for easy of use for the rest of the team.
> 
> I'm excited for this feature! We do this kind of stuff ALL THE TIME, so it will be a huge timesaver!

Thanks. I updated the pr to use the flag way. You can use `-i` or `--account-id` to specify the account id.

**Comment by rogbas** [comment]
@rogbas please build this version and validate it

**Pull request merged**
