### PR TITLE
Support generating AWS account console URL

### PR DESCRIPTION
**Pull request by yeya24**
Fixes https://issues.redhat.com/browse/OSD-3949

There are two ways to specify an AWS account

1. specify the AWS account cr name

```
osd-utils-cli console -a test-cr
```

2. specify the AWS account ID

```
osd-utils console -i <account ID>
```

All supported options:

```
bin/osd-utils-cli console -h
generate a AWS console URL on the fly

Options:
  -i, --account-id='': The AWS account ID we need to create AWS console URL for
  -a, --account-name='': The AWS account cr we need to create AWS console URL for
      --account-namespace='aws-account-operator': The namespace to keep AWS accounts. The default value is
aws-account-operator.
  -r, --aws-region='us-east-1': specify AWS region
  -d, --duration=3600: The duration of the console session. Default value is 3600 seconds(1 hour)

Usage:
  osd-utils-cli console [flags] [options]

Use "osd-utils-cli options" for a list of global command-line options (applies to all commands).

```

### CODE REVIEW

**Comment by rogbas** [comment]
@rogbas @clcollins please test in hive-stage and comment

**Comment by clcollins** [comment]
Testing on hive-stage, unsure if I'm doing something wrong.  Generated a binary and copied over to hive-stage, and attempted the following:

```shell
bin/osd-utils-cli-beta-pr4 console -i 712058710802 -d 900
E0617 18:04:46.475754   89545 iam.go:96] Failed to assume role: ValidationError, 1 validation error detected: Value 'AROAJFUSN7FSGCOJQHDQI:i-06f9e1601fe9e50bc' at 'roleSessionName' failed to satisfy constraint: Member must satisfy regular expression pattern: [\w+=,.@-]* ValidationError: 1 validation error detected: Value 'AROAJFUSN7FSGCOJQHDQI:i-06f9e1601fe9e50bc' at 'roleSessionName' failed to satisfy constraint: Member must satisfy regular expression pattern: [\w+=,.@-]*
	status code: 400, request id: 58fa2177-cbf9-4f0d-a6c9-e30809ef927c
```

**Comment by yeya24** [comment]
> Testing on hive-stage, unsure if I'm doing something wrong. Generated a binary and copied over to hive-stage, and attempted the following:
> 
> ```shell
> [root@hive-stage-master-ip-10-140-2-38.ec2.internal chcollin]# bin/osd-utils-cli-beta-pr4 console -i 712058710802 -d 900
> E0617 18:04:46.475754   89545 iam.go:96] Failed to assume role: ValidationError, 1 validation error detected: Value 'AROAJFUSN7FSGCOJQHDQI:i-06f9e1601fe9e50bc' at 'roleSessionName' failed to satisfy constraint: Member must satisfy regular expression pattern: [\w+=,.@-]* ValidationError: 1 validation error detected: Value 'AROAJFUSN7FSGCOJQHDQI:i-06f9e1601fe9e50bc' at 'roleSessionName' failed to satisfy constraint: Member must satisfy regular expression pattern: [\w+=,.@-]*
> 	status code: 400, request id: 58fa2177-cbf9-4f0d-a6c9-e30809ef927c
> ```

Let me investigate.

**Comment by clcollins** [comment]
Needed to setup my ~/.aws/credentials file and specify the right file/profile:

AWS_SHARED_CREDENTIALS_FILE=<path to creds file> AWS_PROFILE=<profile name> bin/osd-utils-cli-beta-pr4 console -i <account id> -d 900

And the console was generated correctly

**Pull request merged**
