### PR TITLE
CSV output and unit tests for create.go and reconcile.go

### PR DESCRIPTION
**Pull request by nickwyl**
Added CSV output option for viewing costs.

Wrote unit tests for create.go and reconcile.go.

### CODE REVIEW

**Comment by rogbas** [comment]
@nickwyl is it still a work in progress? could you please rebase?

I understand you left RH, lmk if you don't want to be pinged from that PR anymore.

**Comment by nickwyl** [comment]
> @nickwyl is it still a work in progress? could you please rebase?
> 
> 
> 
> I understand you left RH, lmk if you don't want to be pinged from that PR anymore.


Thank you for checking up @rogbas!

Yes, it's still a work in progress. I will rebase and push  a non-draft version next!

**Comment by iamkirkbater** [comment]
/lgtm

Thanks @nickwyl!!!

**Comment by rogbas** [comment]
/lgtm
/approve

Thanks a lot @nickwyl

**Comment by nickwyl** [comment]
Rogerio, Kirk --- thank you!

**Pull request merged**
