### PR TITLE
support aws account credentials secret validation

### PR DESCRIPTION
**Pull request by yeya24**
Signed-off-by: yeya24 <yb532204897@gmail.com>

Fixes https://issues.redhat.com/browse/OSD-4016

This command has two usage.

1. don't have any arguments, then it will check all account secrets

```
osd-utils-cli check-secrets
```

2. have one argument `account name`, then it will validate the credentials associated with this account cr.

```
osd-utils-cli check-secrets <account cr name>
```

### CODE REVIEW

**Comment by yeya24** [comment]
Will update this one after https://github.com/openshift/osd-utils-cli/pull/11 is merged

**Comment by clcollins** [comment]
Looks great!  Can you add a `-v/--verbose` flag to print some output for folks that want it?  Maybe just the secret that is being checked?

Otherwise, I like the quiet, no-output-unless-problem setup!  Old school Linux! :)

**Comment by yeya24** [comment]
There are some conflicts now...

**Comment by clcollins** [comment]
Wonder if this will work:

/approve cancel

**Comment by yeya24** [comment]
Updated @clcollins  It's ok to merge now I think. Let's wait CI green.

**Pull request merged**
